### ISSUE TITLE
permissive -> permissive-

### ISSUE THREAD

**Issue by jpr89** [TheLartians/ModernCppStarter#122]
https://github.com/TheLartians/ModernCppStarter/blob/60769908b67fc9b34848e941314622209c8fb21a/CMakeLists.txt#L51-L52

This line of code is wrong. Being permissive means to let details slide.
permissive- means being conformant.

https://docs.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=msvc-160

**Comment by TheLartians** [comment]
Oh yeah, seems to be a typo that got through code review in #80. 😱 
Thanks for reporting!
