### ISSUE TITLE
Add sanitizer support

### ISSUE THREAD

**Issue by reapler** [TheLartians/ModernCppStarter#13]
Hi, at first thanks for the template project.

Have you considered to add Sanitizer support as well other utilities like Valgrind?
If you would like to add these, i have already created a few projects for personal usage.
I think it might be also useful for you if you want to extend your template:
https://github.com/reapler/Sanitize-Coredump-Coverage
https://github.com/reapler/Memory-Sanitizer-Instrumentation

However i believe there are a few edge cases on my projects (for e.g. shared libraries) where the compilation might fail and a few more cmake modules would look better.
But otherwise it could help to get a better overview of these tools.

**Comment by stanislaw** [comment]
For what is worth, there is also this: https://github.com/StableCoder/cmake-scripts. I am interested to see what the final modern C++ template will look like 👍

**Comment by TheLartians** [comment]
Hey, thanks for the suggestion and the links! I think that adding sanitizer support through the linked scripts could indeed be very useful.
As there are many similar and specific tools that could be added, I've decided to move these to a separate `tools.cmake` script (#14) that fetches and imports the requested scripts on-demand. This avoids bloat as it only fetches the necessary tools and leaves space for further additions in the future.
