### ISSUE TITLE
version.h is missing in include/greeter

### ISSUE THREAD

**Issue by Marco-Israel** [TheLartians/ModernCppStarter#130]
So build fails.

Solution:
Andd a file called include/version/version.h 
with content
 #define GREETER_VERSION "1.0"

**Comment by TheLartians** [comment]
This is an auto generated file based on the project name, please to not create it manually. Please refer to my other [answer](https://github.com/TheLartians/ModernCppStarter/issues/129) and the [*Usage* section of the readme](https://github.com/TheLartians/ModernCppStarter#usage) for instructions how to rename the project.

**Comment by sekoyo** [comment]
I followed those steps except I cloned locally, I don't have a version.h either - how is it supposed to get created? Running the build commands doesn't create it
