### ISSUE TITLE
Support sonarcloud.io

### ISSUE THREAD

**Issue by jayvdb** [TheLartians/ModernCppStarter#131]
https://sonarcloud.io is a SaaS like codecov.io which supports C++ projects, which is free for OSS projects, and the server is also OSS so projects can self-host if they want to avoid problems like https://www.schneier.com/blog/archives/2021/04/backdoor-found-in-codecov-bash-uploader.html

https://www.sonarqube.org/features/multi-languages/cpp/

**Comment by TheLartians** [comment]
Hey thanks for the suggestion! For now I don't believe it's an essential feature to the starter as we already support other common static analysers. However, if you think this has a large value for users, feel free to maintain a custom fork of the starter.
