### ISSUE TITLE
how to generate build file of bazel  in cmake? 

### ISSUE THREAD

**Issue by roderick-liu** [TheLartians/ModernCppStarter#147]
hi 
   how to generate build file of bazel  in cmake?

**Comment by TheLartians** [comment]
Hey, unfortunately I'm not aware of any bazel generator for CMake.

**Comment by ClausKlein** [comment]
https://docs.bazel.build/versions/4.2.1/bazel-overview.html

`bazel` is completely different from `CMake`, witch is a build generator, not a build tool.
