### ISSUE TITLE
The GitHub workflow actions needs an update

### ISSUE THREAD

**Issue by ClausKlein** [TheLartians/ModernCppStarter#160]
## Problem
Run actions/cache@v2
[8](https://github.com/TheLartians/ModernCppStarter/actions/runs/3288189079/jobs/5418225839#step:3:9)
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
[9](https://github.com/TheLartians/ModernCppStarter/actions/runs/3288189079/jobs/5418225839#step:3:10)
Cache not found for input keys: Windows-cpm-modules-8d17b6a5807bef3fb2c80fa8008f8eb7583d7ae9df0c462d2a34e90edc700324

## Solution
upgrade to **v3**:
`actions/cache@v3`

do:
`perl -p -i.bak -e's/v2/v3/;' *.yml`

**Comment by TheLartians** [comment]
Fixed in #163.
