### ISSUE TITLE
Having a issue when adding asio to my project using this template

### ISSUE THREAD

**Issue by tanja84dk** [TheLartians/ModernCppStarter#174]
Hello

I thought I would give this template a chance but I'm unfortunally having issue when the project needs asio

I'm pulling in asio with CPM as I always do with the extra configuration that is listed in the CPM example, but unfortunally since asio don't distribute as a cmake project then I'm facing this issue when trying to add it
```
CMake Error: install(EXPORT "tanja84dk_httplibTargets" ...) includes target "tanja84dk_httplib" which requires target "asio" that is not in any export set.
```

I'm using this way to include it except updated up to the newest version https://github.com/cpm-cmake/CPM.cmake/blob/master/examples/asio-standalone/CMakeLists.txt

Is there a way I'm able to work around it?

**Comment by tanja84dk** [comment]
> https://discourse.cmake.org/t/cmake-error-install-export-projecttargets-includes-target-xxx-which-requires-target-yyy-that-is-not-in-any-export-set/7344

Unfortunally looking at that thread does not help me alot actually got me more confused about it unfortunally specially its first time I'm trying the template ( and PackageProject.cmake since the template rely on it )

Also unfortunally I'm stuck on cmake version 3.22.1 since that is the newest in my build containers version and in that link it talks about cmake 3.26

And also the thing that asio it self doesn't have a CMakeLists.txt also doesn't help me because I have to rely on the examples from CPM

**Comment by ClausKlein** [comment]
You habe to install all packages you depend on.

Try to use this https://github.com/chriskohlhoff/asio/pull/1105 asio Version!

**Comment by tanja84dk** [comment]
No thanks I will not use your branch since its not verifyed by asio's author since its actually imposible to see what version its made for since your branch were started last year, and also gobs as you use in your branch are really no no go

And tbh I chose this night to literally dropped this template completely and gone back to only use CPM because all the issues is started here after I tried to use this template

**Comment by tanja84dk** [comment]
closed

**Comment by ClausKlein** [comment]
Try this, it works:

https://github.com/ClausKlein/ModernCmakeStarter/pull/7/files

**Comment by tanja84dk** [comment]
WHAT THE ACTUALLY FUCK ARE YOU NOT UNDERSTANDINDING YOUR MORON @ClausKlein As I said multiple times and closed the question I left it and went back to former way there always worked and stopped using the template
You are literally actually more brain dead then a person with autism because you you cannot take a no in any way even if something is closed.

STOP IT YOUR FOCKING MORON @ClausKlein !!!!!!!!!!!

**Comment by tanja84dk** [comment]
@ClausKlein Why the fuck cant you take a question is closed and just leave it!!!
