### ISSUE TITLE
github workflow does not support c++2a

### ISSUE THREAD

**Issue by andersfylling** [TheLartians/ModernCppStarter#27]
Just noticed that the latest ubuntu build, for example, uses gcc 7.5 which I don't believe support c++20 features. Eg. here the bit implementation is missing: https://github.com/andersfylling/sorting-nine-inputs-requires-twenty-five-comparisons/runs/605230180?check_suite_focus=true

ubuntu-latest refers to the lts version 18.04, and sadly ubuntu-18.10 is not a valid version. It seems that either the gcc must be updated somehow or just add a quick note in the README.

**Comment by andersfylling** [comment]
I'm looking into how to add the matrix configuration for gcc and clang, ill update you later

**Comment by TheLartians** [comment]
The tests use the default gcc available on the current platform (as it's a good way to ensure compatibility with common build systems), but you can override it to use another version. AFAIK ubuntu-latest supports at least gcc-9. If you want to use that, you can change your action accordingly:

```yaml
    - name: configure
      run: CXX=g++-9 cmake -Htest -Bbuild -DENABLE_TEST_COVERAGE=1
```

and be sure to also use the according version of gcov:

```yaml
    - name: collect code coverage
      run: bash <(curl -s https://codecov.io/bash) -x gcov-9 || echo "Codecov did not collect coverage reports"
```

**Comment by TheLartians** [comment]
I've added a section in the wiki for common problems as well: https://github.com/TheLartians/ModernCppStarter/wiki/Troubleshooting

**Comment by andersfylling** [comment]
perfect!
