### ISSUE TITLE
code template for standalone versioning

### ISSUE THREAD

**Issue by andersfylling** [TheLartians/ModernCppStarter#35]
When releasing a binary, it might be of interest to specify the software version through a cmake variable:
`-DSTANDALONE_VERSION=1.32.1`

I'm not aware what the best practice is for c++ and cmake, but I am aware this can easily be achieved through templates:

```
# CMakeLists.txt
if(NOT STANDALONE_VERSION)
  set(STANDALONE_VERSION "0.0.0")
endif()
configure_file("${CMAKE_CURRENT_SOURCE_DIR}/version.template.h" "${CMAKE_CURRENT_SOURCE_DIR}/src/version.h")
```

```c++
// version.template.h
#pragma once

// clang-format off
const auto version{"@STANDALONE_VERSION@"};
// clang-format on
```

The `version.h` can then be included in the `main.cpp` file, allowing the standalone version to be printed out when needed. eg. `myapp --version`.

**Comment by TheLartians** [comment]
Hm interesting idea, personally I would bind it to the project version already defined in the CMakeLists. However I'm unaware what the current best practices are in this domain. I can imagine some projects preferring a header in the library's public includes defining the version number. I'll look at how other libraries handle this problem and see if we can find a good general solution for the starter.
