### ISSUE TITLE
cmake test for c++2a concepts

### ISSUE THREAD

**Issue by andersfylling** [TheLartians/ModernCppStarter#38]
How about an optional cmake script that can test for concepts support?

Maybe something like :
```CMake
include(CheckCXXSourceCompiles)

macro(SUPPORT_CONCEPTS VAR)
    check_cxx_source_compiles("
#include <iostream>

template <typename T, typename = void>
struct is_something : std::false_type {};

template <typename T>
concept SpecialType = is_something<T>::value;


int main() {
  return 0;
}
" ${VAR})
endmacro()
```

Then just include it and check if the var is true.

**Comment by TheLartians** [comment]
Hey thanks for the suggestion! I can see how this can be useful for conditionally configuring projects depending on the compiler's experimental feature set.
However, I feel that this is a bit too niche to be included in a general starter template. What would probably make more sense imo is to create a separate repo with such feature tests that could easily be included using CPM.cmake.

**Comment by andersfylling** [comment]
Is there a recommended way to specify the minimum c++ version for the library code?

**Comment by andersfylling** [comment]
Sorry! I'm just a bit code blind!
