### ISSUE TITLE
Static analyzis

### ISSUE THREAD

**Issue by andersfylling** [TheLartians/ModernCppStarter#39]
Have you considered triggering static analysis on build? Gcc and clang supports that now I believe?

Just saw another reddit add cppcheck to his template project and thought it could be interesting.

**Comment by TheLartians** [comment]
Hey thanks for the request, static analysis would be a great addition to the starter!
Unless there are other suggestions, I'll look at adding [StableCoder's CMake tools](https://github.com/StableCoder/cmake-scripts/blob/master/tools.cmake) to the project (in the same way as current sanitiser support).
