### ISSUE TITLE
USE_<TOOL> defines cause a warning

### ISSUE THREAD

**Issue by friendlyanon** [TheLartians/ModernCppStarter#57]
### Steps to reproduce:
* Make a new project
* `cmake -Hall -Bbuild -DUSE_CCACHE=ON`

### Expected output:
No warnings.

### Actual output:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    USE_CCACHE
```

**Comment by TheLartians** [comment]
Good catch! When the tools were originally written, they were intended to be included by the main library and needed to be excluded when used as a third-party dependency. As we are now only importing tools from subprojects, the restriction should not be necessary anymore.

**Comment by TheLartians** [comment]
On second thought, the flags we are setting should be scoped for the whole project, so the best solution would be to simply include the tools from the "all" subproject as well.
