### ISSUE TITLE
Why is style check done locally, but not in github actions?

### ISSUE THREAD

**Issue by MBkkt** [TheLartians/ModernCppStarter#62]
https://github.com/MBkkt/cppformlang/runs/1081779937

And how run a documentation workflow?

**Comment by MBkkt** [comment]
Sorry, copy-paste problem, but it would be nice if cmake-format runs for all files in the repository

**Comment by TheLartians** [comment]
Glad to hear you resolved it! 
CMake-format should actually run for all (C++ / CMake) files in the repository. 
Can you perhaps give some more details on what didn't work?

**Comment by MBkkt** [comment]
@TheLartians I think fix-cmake-format doesn't work for CPM.cmake, but check-cmake-format works, may be for include or something

Try change CPM.cmake and do fix-cmake-format

**Comment by TheLartians** [comment]
Are you using the newest version of the starter? In an old version we had excluded `CPM.cmake`, but this has been changed recently. If you're `test/CMakeLists.txt` contain an exclude pattern for `CPM.cmake`, you could try removing that. I'd also recommend updating to the newest version of `CPM.cmake` by running

```
mkdir -p cmake
wget -O cmake/CPM.cmake https://github.com/TheLartians/CPM.cmake/releases/latest/download/get_cpm.cmake
```

in the project root.

**Comment by MBkkt** [comment]
I think yes, I am using the same as in the your template current master

**Comment by TheLartians** [comment]
That's strange then, for me in does format all files 🤔

**Comment by MBkkt** [comment]
I use arch linux may be problem in this
