### ISSUE TITLE
Running doxygen command on windows

### ISSUE THREAD

**Issue by garrettseepersad** [TheLartians/ModernCppStarter#68]
I was trying to compile Doxygen on my windows machine and I have installed Doxygen, jinja2 and Pygments . The following is the error message I received after running the command below. Any suggestions on how to resolve the issue?

Command :  `cmake --build build/doc --target GenerateDocs`

> 
> AzureAD+GS@DESKTOP-JMINGW64 ~/Documents/GIT/ModernCppStarter (feature/architecture_drawing)
> $ cmake --build build/doc --target GenerateDocs
> Microsoft (R) Build Engine version 16.8.2+25e4d540b for .NET Framework
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
>   Checking File Globs
> CUSTOMBUILD : warning : libgs not found [C:\Users\GS\Documents\GIT\ModernCppStarter\build\doc\GenerateDocs.vcxproj]
>   Traceback (most recent call last):
>     File "C:\Users\GS\Documents\GIT\ModernCppStarter\build\doc\_deps\mcss-src\documentation\doxygen.py", line 3857, in <module>
>       subprocess.run(["doxygen", doxyfile], cwd=os.path.dirname(doxyfile), check=True)
>     File "C:\Python38\lib\subprocess.py", line 489, in run
>       with Popen(*popenargs, **kwargs) as process:
>     File "C:\Python38\lib\subprocess.py", line 854, in __init__
>       self._execute_child(args, executable, preexec_fn, close_fds,
>     File "C:\Python38\lib\subprocess.py", line 1307, in _execute_child
>       hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
>   FileNotFoundError: [WinError 2] The system cannot find the file specified
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(238,5): error MSB8066: Custom build for 'C:\Users\GS\Documents\GIT\ModernCppStarter\build\doc\CMakeFiles\5d6b58ea6af2e68a3fc47579611072b8\GenerateDocs.rule' exited with code 1. [C:\Users\GS\Documents\GIT\ModernCppStarter\build\doc\GenerateDocs.vcxproj]
> 

`

**Comment by TheLartians** [comment]
Hm unfortunately I don't have Windows, so I can't reproduce the issue, but have you installed Doxygen and necessary python dependencies?

usually,

```bash
pip3 install jinja2 Pygments
```

but as the error saus `libgs not found`, perhaps also

```
pip3 install libgs
``` 

would work.

**Comment by garrettseepersad** [comment]
Tried, but libgs had some older version requirements :(

Unfortunately don't have the time to look further into it. I am okay with compiling on Linux.

Thanks for creating the boiler-plate.... it's a life saver
