### ISSUE TITLE
Gitlab CI

### ISSUE THREAD

**Issue by dbonattoj** [TheLartians/ModernCppStarter#97]
I see you are writing a script to automatically configure a new project,

It would be nice to be able to choose between Github Actions and Gitlab CI as they are very similar
https://docs.github.com/en/actions/learn-github-actions/migrating-from-gitlab-cicd-to-github-actions#:~:text=Both%20GitLab%20CI%2FCD%20and,with%20the%20runs%2Don%20key.

Bests,

**Comment by TheLartians** [comment]
Thanks for the suggestion! I haven't yet looked too much into the script automation as the project still seems easy enough to adapt as is, but I'll keep the choice of CI in mind if I eventually get to it.

**Comment by TheLartians** [comment]
I probably won't be adding the script after all, due to the increased maintenance and low gains (imo it's good for users to familiarise themselves with CMake / CI which this template should make very easy). It may be a good idea to create a Gitlab compatible fork of this project though.
