### ISSUE TITLE
gitignore proposition

### ISSUE THREAD

**Issue by dbonattoj** [TheLartians/ModernCppStarter#99]
Proposition for the .gitignore:

```
# Build
/build*

# Project files
/.vscode

# CPM modules
/cpm_modules

# Log files
*.log

# Generated by MacOS
.DS_Store

# Generated by Windows
Thumbs.db

# Applications
*.app
*.exe
*.war

# Large media files
*.xlsx
*.docx
*.pdf
*.mp4
*.tiff
*.avi
*.flv
*.mov
*.wmv
```

Bests,

**Comment by TheLartians** [comment]
The Gitignore is very project specific, e.g. I can imagine projects where I'd like to track a PDF or even a .mov into version control. Imo it's better to keep minimal assumptions for now and let users adapt it to their needs.
